
easy_admin:
    entities:
        Observation:
            disabled_actions: ['new','edit','view','search']
            class: App\Entity\Observation
            label: 'Observations'
            roles: ['ROLE_NATURALISTE']
            list:
                fields:
                  - { property: 'user', label: 'Pseudo' }
                  - { property: 'bird', label: 'Oiseau' }
                  - date
                  - { property: 'valid', label: 'Validée'}
                actions: 
                    - { name: 'show', label: "Voir l'observation", icon: 'user' }
                    - { name: 'delete', label: "Suprimer l'observation", icon: 'remove' }
                sort: ['date', 'DESC']    
            templates:
                show: 'admin/checkObservation.html.twig'
            dashboard: ["bird", "user", "date"]
                



        Bird:
            disabled_actions: ['new','edit']
            class: App\Entity\Bird
            label: 'Contribution'
            roles: ['ROLE_NATURALISTE']
            dashboard: ["name", "contributor"]
            list:
                dql_filter: 'entity.description = false' #description non nul
                fields:
                    - { property: 'name', label: 'Oiseau'}
                    - { property: 'contributor', label: 'Contributeur'}
                    - { property: 'description', label: 'Description'}
                    - { property: 'descriptionValid', label: 'Validée'}
                actions: 
                    - { name: 'show', label: "Voir la contribution", icon: 'user' }
                    - { name: 'delete', label: "Supprimer", icon: 'remove' }
            templates:
                show: 'admin/checkContribution.html.twig'

        Article:
            disabled_actions: ['search']
            class: App\Entity\Article
            label: 'Articles'
            roles: ['ROLE_REDACTEUR']
            dashboard: ["title", "author"]
            list:
                fields:
                    - { property: 'title', label: 'Titre'}
                    - { property: 'author', label: 'Auteur'}
                    - { property: 'date', label: 'Date'}
                actions: 
                    - { name: 'edit', label: "Editer l'article", icon: 'edit' }
                    - { name: 'delete', label: "Supprimer", icon: 'remove' }
            form: 
                fields:
                    - title
                    - { property: 'content', css_class: 'awesome-ckeditor', type: 'textarea' }
                    - { property: 'images', type: 'collection', type_options: { entry_type: 'App\Form\ImageType' }}
                    - { property: 'category', type: 'choice', type_options: {expanded: true, multiple: true, choices: { 'Mise en avant':'trend', 'Description Asso':'documentation'  }}}
        User:
            class: App\Entity\User
            label: 'Utilisateurs'
            disabled_actions: ['new', 'edit']
            roles: ['ROLE_ADMIN_SUPER']
            dashboard: ["avatar","username"]
            list:
                fields:
                  - { property: 'avatar', type: 'image', base_path: '/images/avatar' }
                  - { property: 'username', label: 'Pseudo' }
                  - email
                  - { property: 'formatedRoles', label: 'Roles' }
                actions:
                  - { name: 'checkProfil', label: 'Voir le profil', icon: 'user' }
                  - { name: 'delete', label: "Supprimer", icon: 'remove' }
            edit:
                fields:
                    - roles          

           
    design:
        brand_color: '#1e5d93'
        templates:
            layout: "admin/layout.html.twig"
            menu:   "admin/menu.html.twig"
        assets:    
            js:
                - '/dist/js/ckeditor5/ckeditor.js.map'
                - '/dist/js/ckeditor5/ckeditor.js'
                - '/dist/js/ckeditor5/ckeditorInit.js'

        menu:
            - { label: 'Dashboard', route: 'admin_dashboard', default: true }
            #- { label: 'Accueil', route: 'homepage', icon: 'home' }
            - { entity: 'User', icon: 'user' }
            - { entity: 'Observation', icon: 'camera' }
            - { entity: 'Article', icon: 'newspaper-o' }
            - { entity: 'Bird', icon: 'pencil-square' }
